services:
  web:
    build:
      dockerfile: ./web.Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - database
    
  parser:
    build:
      dockerfile: ./parser.Dockerfile
    env_file:
      - .env
    depends_on:
      - database
      - web

  database:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password


volumes:
  pg_data: