# Generated by Django 4.2.7 on 2023-11-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_url", models.TextField(unique=True)),
                ("title", models.TextField()),
                ("body", models.TextField()),
                ("author_url", models.TextField()),
                ("author_username", models.TextField()),
                ("published_at", models.DateTimeField()),
                ("hub", models.TextField()),
            ],
            options={
                "db_table": "articles",
            },
        ),
        migrations.CreateModel(
            name="Hub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hub_url", models.TextField(unique=True)),
            ],
            options={
                "db_table": "hubs",
            },
        ),
    ]
